# Generated by Django 4.2.13 on 2024-05-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=150, null=True)),
                ('year_founded', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('size_range', models.CharField(blank=True, max_length=20, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=100, null=True)),
                ('current_estimate', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_estimate', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64)),
                ('task_state', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
            ],
        ),
    ]
